version: 2.1
jobs:
  lint-test:
    docker:
      - image: circleci/node:12.18.2
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn lint
      - run: yarn test:ci
workflows:
  lint-test:
    jobs: 
      - lint-test